name: operational-mocks
version: "0.1"

dependencies:
  - base
  - operational
  - hspec

ghc-options:
  - -Wall
  - -Werror
  - -fno-warn-name-shadowing

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    ghc-options:
      - -fdefer-typed-holes
    dependencies:
      - HUnit

library:
  source-dirs:
    - src
