name: free-mocks
version: "0.1"

dependencies:
  - base
  - free
  - hspec
  - transformers

ghc-options: >
  -Wall
  -fno-warn-name-shadowing

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src

library:
  source-dirs:
    - src
